# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_authorproxy_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='salutation',
            field=models.CharField(max_length=50),
        ),
    ]
